### ISSUE TITLE
Doesn't support 'learn.microsoft.com'

### ISSUE THREAD

**Issue by lukemurraynz** [mjisaak/skilling-champion-extension#33]
After a recent change by Microsoft, docs.microsoft.com - is being redirected to: learn.microsoft.com (supposedly, the creator IDs are still supported) but this extension doesn't currently include the learn.microsoft.com.

**Comment by mjisaak** [comment]
Hi @lukemurraynz,

I was waiting for Microsoft to confirm that learn.microsoft.com is tracked by the skilling champion program. It looks like that this is the case. This issue is fixed with PR #32 . I already released the versions to the chrome, edge and firefox marketplaces - it will take a little bit until they validate it....

Best regards,
Martin
